name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Check out code
    - name: Put current date into a variable
      run: |
        $NOW=& Get-Date -format yyyy-MM-dd
        echo "NOW=$NOW" >> $env:GITHUB_ENV
    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
        image: yaming116/stt
        context: .
        labels: |-
          org.opencontainers.image.source=https://github.com/${{ github.repository }}
          org.opencontainers.image.revision=${{ github.sha }}
        tags: ${{env.NOW}}, latest
        registry: docker.io
        dockerfile: Dockerfile
        platforms: linux/amd64,linux/arm64
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
